### ISSUE TITLE
Just curious - how is it different from others

### ISSUE THREAD

**Issue by Noitidart** [scottgonzalez/sane-email-validation#15]
Thanks for this awesome lib. I've been using it for years but today was just curious what makes this different from the others. I peaked at the readme and it just says its "sane" haha. Could you please share how so? Love the lib, thanks for it!

**Comment by scottgonzalez** [comment]
It's been a long time since I wrote this, so I'm not quite sure 😛  But I'm fairly confident the first set of invalid tests covers a lot of the differences from other validations:

https://github.com/scottgonzalez/sane-email-validation/blob/1971fbb5d55833d4f1b0385ee2e8eb8a4f0ae4b8/test/index.js#L17-L32

The main problem is that what's actually valid as an email address and what people realistically use as an email address are very different.

**Comment by Noitidart** [comment]
Haha thanks very much!
